# Persistence mode: DB \u044D\u0441\u0432\u044D\u043B MEM \u0433\u044D\u0436 \u0441\u043E\u043B\u044C\u0436 \u0431\u043E\u043B\u043D\u043E
app.persistence.mode=DB

# H2 database driver
db.driver=org.h2.Driver

# H2 local file database
db.url=jdbc:h2:./data/assignment_db

# Database username
db.user=sa

# Database password
db.password=